---
- name: Setup Computer
  hosts: "{{ target_ip }}"
  tasks:
    - include_tasks: ./playbooks/CoreSetup.yml
    - include_tasks: ./playbooks/DockerSetup.yml
    - include_tasks: ./playbooks/Extras.yml
