---
- name: Setup Computer
  hosts: "{{ target_ip }}"
  tasks:
   - include: ./playbooks/CoreSetup.yml
   # - include: ./playbooks/DockerSetup.yml
   # - include: ./playbooks/Extras.yml
   # - include: ./playbooks/Dotfiles.yml
