- name: Check for existing diff-so-fancy repo
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.diff-so-fancy"
  register: diffsofancy
- name: Clone diff-so-fancy
  shell: |
      git clone https://github.com/so-fancy/diff-so-fancy.git {{ ansible_env.HOME }}/.diff-so-fancy
  when: not diffsofancy.stat.exists
