- name: Create git config directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/git"
    state: directory
- name: Create nvim config directories
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/nvim/lua"
    state: directory
- name: Check for existing dotfiles repo
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.dotfiles"
  register: dotfiles
- name: Clone dotfiles
  ansible.builtin.shell: |
      git clone https://github.com/princeodd47/dotfiles.git {{ ansible_env.HOME }}/.dotfiles
  when: not dotfiles.stat.exists
- name: Create .config directory for flake8 config file
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory
- name: Install dotfiles
  ansible.builtin.shell: |
    "{{ ansible_env.HOME}}/.dotfiles/install"
  when: not dotfiles.stat.exists
