- name: Install pyenv requirements
  become: true
  ansible.builtin.package:
    name:
      - git
      - make
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - wget
      - curl
      - llvm
      - libncurses5-dev
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libffi-dev
      - liblzma-dev
      - python3-openssl
    state: latest
    update_cache: yes
- name: Check if .pyenv directory exists
  stat:
      path: "{{ ansible_env.HOME }}/.pyenv"
  register: pyenv_dir
- name: Clone pyenv
  when: not pyenv_dir.stat.exists
  shell: >
      git clone https://github.com/pyenv/pyenv.git ~/.pyenv
  args:
    warn: false
- name: Install pyenv
  when: not pyenv_dir.stat.exists
  shell: >
      cd ~/.pyenv && src/configure && make -C src
  args:
    warn: false
- name: Install Python
  when: not pyenv_dir.stat.exists
  shell: |
      . "{{ ansible_env.HOME }}/.bash_config"
      /home/spowell/.pyenv/bin/pyenv install 3.8.10
      /home/spowell/.pyenv/bin/pyenv install 3.7.4
      /home/spowell/.pyenv/bin/pyenv install 2.7.18
- name: Set global Python verion
  ansible.builtin.shell:
    cmd:  /home/spowell/.pyenv/bin/pyenv global 3.8.10
- name: Check if pyenv-virutalenv directory exists
  stat:
      path: "{{ ansible_env.HOME }}/.pyenv/plugins/pyenv-virtualenv"
  register: pyenv_virtualenv_dir
- name: Clone pyenv
  when: not pyenv_virtualenv_dir.stat.exists
  shell: >
      git clone https://github.com/pyenv/pyenv-virtualenv.git "{{ ansible_env.HOME }}/.pyenv/plugins/pyenv-virtualenv"
  args:
    warn: false
