- name: Install core applications
  become: true
  ansible.builtin.package:
    name:
      - git
      - htop
      - silversearcher-ag
      - tmux
      - tree
      - unzip
      - vim
    state: latest
    update_cache: yes
- name: Add bash_config to bashrc
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    block: |
      if [ -f ~/.bash_config ]; then
          . ~/.bash_config
      fi
- include_tasks: ./core_setup/BashGitPrompt.yml
- include_tasks: ./core_setup/Dotfiles.yml
- include_tasks: ./core_setup/NeoVim.yml
- include_tasks: ./core_setup/NVM.yml
- include_tasks: ./core_setup/PyEnv.yml
- include_tasks: ./core_setup/Poetry.yml
