- name: Install core applications
  become: true
  package:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
  - git
  - htop
  - silversearcher-ag
  - tmux
  - vim
- name: Add bash_config to bashrc
  blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    block: |
      if [ -f ~/.bash_config ]; then
          . ~/.bash_config
      fi
- include: ./core_setup/BashGitPrompt.yml
- include: ./core_setup/Dotfiles.yml
- include: ./core_setup/PyEnv.yml
